# Set true color
set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm*:Tc"

# Plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'mocha'   # mocha, macchiato, frappe, latte

set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tpm/tpm'
